/**
 * Purpose: Generate or verify the explicit Rehearsal export-boundary migration from
 * the reviewed sanitization manifest.
 * Run: `npm run rehearsal:export-migration:generate` or
 * `npm run rehearsal:export-migration:check`.
 */

import { readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";

const manifestPath = fileURLToPath(
	new URL(
		"../../../infrastructure/rehearsal/application/sanitization-policy.json",
		import.meta.url,
	),
);
const migrationPath = fileURLToPath(
	new URL(
		"../../../supabase/migrations/20260912143000_rehearsal_export_boundary.sql",
		import.meta.url,
	),
);
const mode = process.argv[2] ?? "--check";
const identifierPattern = /^[a-z][a-z0-9_]{0,62}$/u;

if (!new Set(["--check", "--write"]).has(mode)) {
	throw new Error("Use --check or --write for the Rehearsal export migration.");
}

const quoteIdentifier = (value) => {
	if (!identifierPattern.test(value)) {
		throw new Error(`Unsafe Rehearsal migration identifier: ${value}`);
	}
	return `"${value}"`;
};

const manifest = JSON.parse(await readFile(manifestPath, "utf8"));
const includedTables = manifest.tables.filter(
	(table) => table.sourceRows !== "EXCLUDE",
);
for (const table of includedTables) {
	if (table.columns.some((column) => column.action === "EXCLUDE")) {
		throw new Error(
			`Included export table ${table.name} contains a column classified EXCLUDE.`,
		);
	}
}

const standardSchemaRoles = [
	"anon",
	"authenticated",
	"service_role",
	"supabase_admin",
	"supabase_auth_admin",
	"supabase_functions_admin",
	"supabase_storage_admin",
	"dashboard_user",
];
const tableSql = includedTables
	.map((table) => {
		const tableName = quoteIdentifier(table.name);
		const columns = table.columns
			.map((column) => quoteIdentifier(column.name))
			.join(",\n\t");
		const viewName = quoteIdentifier(`${table.name}_v1`);
		return `grant select (
	${columns}
) on table public.${tableName} to rehearsal_export_owner;

drop policy if exists rehearsal_export_owner_read on public.${tableName};
create policy rehearsal_export_owner_read
	on public.${tableName}
	for select
	to rehearsal_export_owner
	using (true);

create view rehearsal_export.${viewName}
	with (security_barrier = true, security_invoker = false)
as
	select
		${columns}
	from public.${tableName};
revoke all on rehearsal_export.${viewName} from public;
grant select on rehearsal_export.${viewName} to rehearsal_export_reader;
alter view rehearsal_export.${viewName} owner to rehearsal_export_owner;`;
	})
	.join("\n\n");

const sql = `-- Generated by scripts/generators/rehearsal/generate_export_boundary_migration.mjs.
-- Do not edit this migration by hand. The reviewed manifest is its source.

do $roles$
begin
	if not exists (select 1 from pg_roles where rolname = 'rehearsal_export_owner') then
		create role rehearsal_export_owner
			nologin nosuperuser nocreatedb nocreaterole noinherit noreplication nobypassrls;
	end if;
	if not exists (select 1 from pg_roles where rolname = 'rehearsal_export_reader') then
		create role rehearsal_export_reader
			nologin nosuperuser nocreatedb nocreaterole noinherit noreplication nobypassrls;
	end if;
	if not exists (select 1 from pg_roles where rolname = 'rehearsal_storage_reader') then
		create role rehearsal_storage_reader
			nologin nosuperuser nocreatedb nocreaterole noinherit noreplication nobypassrls;
	end if;
end;
$roles$;

do $role_invariants$
begin
	if exists (
		select 1
		from pg_roles
		where rolname in ('rehearsal_export_owner', 'rehearsal_export_reader', 'rehearsal_storage_reader')
			and (rolcanlogin or rolsuper or rolcreatedb or rolcreaterole or rolinherit or rolreplication or rolbypassrls)
	) then
		raise exception 'A Rehearsal export role exists with unsafe capabilities';
	end if;
end;
$role_invariants$;

-- PostgreSQL's implicit PUBLIC role cannot express a deny. Remove the broad schema and
-- temporary-object capabilities, then restore them explicitly to the maintained
-- Supabase roles that own normal application and platform behavior.
revoke create, temporary on database postgres from public;
revoke create on schema public from public;
revoke usage on schema public from public;
revoke usage on schema net from public;
revoke execute on all functions in schema net from public;
${standardSchemaRoles
	.map((role) => `grant usage on schema public to ${role};`)
	.join("\n")}
${standardSchemaRoles
	.map((role) => `grant temporary on database postgres to ${role};`)
	.join("\n")}

create schema if not exists rehearsal_export authorization postgres;
revoke all on schema rehearsal_export from public;
revoke all on all tables in schema rehearsal_export from public;
revoke all on all sequences in schema rehearsal_export from public;
revoke execute on all functions in schema rehearsal_export from public;
alter default privileges for role postgres in schema rehearsal_export
	revoke all on tables from public;
alter default privileges for role postgres in schema rehearsal_export
	revoke all on sequences from public;
alter default privileges for role postgres in schema rehearsal_export
	revoke execute on functions from public;

grant usage, create on schema rehearsal_export to rehearsal_export_owner;
grant usage on schema rehearsal_export to rehearsal_export_reader;
grant usage on schema public to rehearsal_export_owner;
grant usage on schema supabase_migrations to rehearsal_export_owner;
grant usage on schema extensions to rehearsal_export_owner;
grant select (version, name, statements)
	on table supabase_migrations.schema_migrations
	to rehearsal_export_owner;

grant rehearsal_export_owner to postgres with inherit false, set true;

create table if not exists rehearsal_export.source_scopes (
	login_role name primary key,
	owner_user_id uuid not null references auth.users(id) on delete restrict,
	owner_email_sha256 text not null check (owner_email_sha256 ~ '^[a-f0-9]{64}$')
);
revoke all on rehearsal_export.source_scopes from public;
grant select on rehearsal_export.source_scopes to rehearsal_export_owner;

create view rehearsal_export.source_scope_v1
	with (security_barrier = true, security_invoker = false)
as
	select owner_user_id, owner_email_sha256
	from rehearsal_export.source_scopes
	where login_role = session_user;
revoke all on rehearsal_export.source_scope_v1 from public;
grant select on rehearsal_export.source_scope_v1 to rehearsal_export_reader;
alter view rehearsal_export.source_scope_v1 owner to rehearsal_export_owner;

-- Storage bytes use a separate short-lived Auth JWT and remain governed by RLS.
-- The role has SELECT only: no object mutation capability and no source application
-- schema access. Its dedicated Auth user is provisioned out of band with the one
-- approved owner UUID in protected app_metadata.
grant rehearsal_storage_reader to authenticator with inherit true, set true;
grant usage on schema storage to rehearsal_storage_reader;
grant select on table storage.buckets, storage.objects to rehearsal_storage_reader;
drop policy if exists rehearsal_storage_reader_read on storage.objects;
create policy rehearsal_storage_reader_read
	on storage.objects
	for select
	to rehearsal_storage_reader
	using (
		bucket_id = 'food-image-assets'
		or (
			bucket_id in ('profile-avatars', 'product-submission-evidence')
			and (storage.foldername(name))[1] =
				(auth.jwt() -> 'app_metadata' ->> 'rehearsal_owner_user_id')
		)
	);

${tableSql}

create view rehearsal_export.migration_history_v1
	with (security_barrier = true, security_invoker = false)
as
	select
		version,
		name,
		coalesce(array_length(statements, 1), 0) as statement_count,
		encode(
			extensions.digest(
				convert_to(array_to_json(statements)::text, 'UTF8'),
				'sha256'
			),
			'hex'
		) as statement_sha256
	from supabase_migrations.schema_migrations;
revoke all on rehearsal_export.migration_history_v1 from public;
grant select on rehearsal_export.migration_history_v1 to rehearsal_export_reader;
comment on view rehearsal_export.migration_history_v1 is
	'Content-only applied migration receipt; raw migration statements are not exported.';
alter view rehearsal_export.migration_history_v1 owner to rehearsal_export_owner;

revoke create on schema rehearsal_export from rehearsal_export_owner;
revoke rehearsal_export_owner from postgres;

comment on schema rehearsal_export is
	'Non-Data-API, versioned, read-only source projections for sanitized Rehearsal refreshes.';
comment on role rehearsal_storage_reader is
	'Read-only Storage JWT role for public product assets and one approved Rehearsal owner prefix.';
`;

if (mode === "--write") {
	await writeFile(migrationPath, sql, { encoding: "utf8", mode: 0o644 });
	console.log(
		`Wrote ${includedTables.length} explicit export views to the Rehearsal boundary migration.`,
	);
} else {
	let current;
	try {
		current = await readFile(migrationPath, "utf8");
	} catch {
		throw new Error(
			"The Rehearsal export-boundary migration is missing. Generate and review it explicitly.",
		);
	}
	if (current !== sql) {
		throw new Error(
			"The Rehearsal export-boundary migration differs from the reviewed sanitization manifest.",
		);
	}
	console.log(
		`Verified ${includedTables.length} explicit export views in the Rehearsal boundary migration.`,
	);
}
