/* eslint-disable */
/**
 * GENERATED REFERENCE FILE — DO NOT IMPORT IN APP CODE.
 *
 * API: USDA FoodData Central
 * Generated by: scripts/generate_api_structures.mjs
 * Query source: observed Supabase API seed data, unless explicit --query values were passed.
 * Sample queries: whole milk, 2 percent milk, greek yogurt
 *
 * Purpose:
 * - Document every field observed in sampled external API responses.
 * - Help future refactors understand vendor payload shape before creating app-owned types.
 *
 * Runtime rule:
 * - These reference types are documentation only.
 * - If app code needs importable types, create curated runtime types under src/lib/types
 *   or the relevant src/lib/utils domain instead of importing this file.
 */


export type FoodDataCentralSearchResponse = {
	aggregations: {
		dataType: {
			Branded: number;
			Experimental?: number;
			Foundation: number;
			"SR Legacy": number;
			"Survey (FNDDS)": number;
		};
		nutrients: Record<string, never>;
	};
	currentPage: number;
	foods: Array<{
		additionalDescriptions?: string;
		allHighlightFields: string;
		brandName?: string;
		brandOwner?: string;
		commonNames?: string;
		dataSource?: string;
		dataType: string;
		description: string;
		fdcId: number;
		finalFoodInputFoods: Array<unknown>;
		foodAttributes: Array<unknown>;
		foodAttributeTypes: Array<unknown>;
		foodCategory: string;
		foodMeasures: Array<unknown>;
		foodNutrients: Array<{
			dataPoints?: number;
			derivationCode: string;
			derivationDescription: string;
			derivationId: number;
			foodNutrientId: number;
			foodNutrientSourceCode: string;
			foodNutrientSourceDescription: string;
			foodNutrientSourceId: number;
			indentLevel: number;
			nutrientId: number;
			nutrientName: string;
			nutrientNumber: string;
			percentDailyValue?: number;
			rank: number;
			unitName: string;
			value: number;
		}>;
		foodVersionIds: Array<unknown>;
		gtinUpc?: string;
		householdServingFullText?: string;
		ingredients?: string;
		marketCountry?: string;
		microbes: Array<unknown>;
		modifiedDate?: string;
		ndbNumber?: number;
		packageWeight?: string;
		publishedDate: string;
		score: number;
		servingSize?: number;
		servingSizeUnit?: string;
		shortDescription?: string;
		subbrandName?: string;
		tradeChannels?: Array<string>;
	}>;
	foodSearchCriteria: {
		dataType: Array<string>;
		foodTypes: Array<string>;
		generalSearchInput: string;
		numberOfResultsPerPage: number;
		pageNumber: number;
		pageSize: number;
		query: string;
		requireAllWords: boolean;
	};
	pageList: Array<number>;
	totalHits: number;
	totalPages: number;
};

export type FoodDataCentralFoodDetailResponse = {
	availableDate: string;
	brandedFoodCategory: string;
	brandName?: string;
	brandOwner: string;
	dataSource: string;
	dataType: string;
	description: string;
	discontinuedDate: string;
	fdcId: number;
	foodAttributes: Array<{
		id: number;
		name: string;
		value: number;
	}>;
	foodClass: string;
	foodComponents: Array<unknown>;
	foodNutrients: Array<{
		amount: number;
		foodNutrientDerivation: {
			code: string;
			description: string;
			id: number;
		};
		id: number;
		nutrient: {
			id: number;
			name: string;
			number: string;
			rank: number;
			unitName: string;
		};
		type: string;
	}>;
	foodPortions: Array<unknown>;
	foodUpdateLog: Array<{
		availableDate: string;
		brandedFoodCategory: string;
		brandName?: string;
		brandOwner: string;
		dataSource: string;
		dataType: string;
		description: string;
		discontinuedDate: string;
		fdcId: number;
		foodAttributes: Array<unknown>;
		foodClass: string;
		gtinUpc: string;
		householdServingFullText: string;
		ingredients: string;
		marketCountry: string;
		modifiedDate: string;
		notaSignificantSourceOf?: string;
		packageWeight?: string;
		publicationDate: string;
		servingSize: number;
		servingSizeUnit: string;
		shortDescription?: string;
		subbrandName?: string;
	}>;
	gtinUpc: string;
	householdServingFullText: string;
	ingredients: string;
	labelNutrients: {
		addedSugar?: {
			value: number;
		};
		calcium: {
			value: number;
		};
		calories: {
			value: number;
		};
		carbohydrates: {
			value: number;
		};
		cholesterol: {
			value: number;
		};
		fat: {
			value: number;
		};
		fiber: {
			value: number;
		};
		iron: {
			value: number;
		};
		potassium?: {
			value: number;
		};
		protein: {
			value: number;
		};
		saturatedFat: {
			value: number;
		};
		sodium: {
			value: number;
		};
		sugars: {
			value: number;
		};
		transFat: {
			value: number;
		};
		vitaminD?: {
			value: number;
		};
	};
	marketCountry: string;
	modifiedDate: string;
	packageWeight?: string;
	publicationDate: string;
	servingSize: number;
	servingSizeUnit: string;
	shortDescription?: string;
	subbrandName?: string;
};
