/**
 * Purpose: Define the maintained source requests, seed queries, serving units, aliases,
 * and standards codes consumed by product-reference discovery. This module contains seed
 * inputs only and does not contact APIs or write the database by itself.
 * Do not run directly; use `npm run seed:product-reference-data`.
 */

export const PRODUCT_REFERENCE_QUERIES = [
	"milk",
	"yogurt",
	"cereal",
	"bread",
	"juice",
	"beans",
	"chicken",
	"salmon",
	"spinach",
	"protein powder",
	"rice",
	"nuts",
	"soda",
	"soup",
	"fruit",
];

export const PRODUCT_DATA_SOURCE_REQUESTS = [
	{
		key: "usda",
		displayName: "USDA FoodData Central",
		sourceType: "external_api",
		homepageUrl: "https://fdc.nal.usda.gov/",
		apiBaseUrl: "https://api.nal.usda.gov/fdc/v1",
		termsUrl: "https://fdc.nal.usda.gov/data-documentation.html",
		attributionText: "USDA FoodData Central",
	},
	{
		key: "open-food-facts",
		displayName: "Open Food Facts",
		sourceType: "external_api",
		homepageUrl: "https://world.openfoodfacts.org/",
		apiBaseUrl: "https://world.openfoodfacts.org/api/v2",
		termsUrl: "https://world.openfoodfacts.org/terms-of-use",
		attributionText: "Open Food Facts contributors",
	},
	{
		key: "ucum-nlm",
		displayName: "Unified Code for Units of Measure (UCUM) at NLM",
		sourceType: "standards_api",
		homepageUrl: "https://ucum.nlm.nih.gov/ucum-service.html",
		apiBaseUrl: "https://ucum.nlm.nih.gov/ucum-service/v1",
		termsUrl: "https://www.nlm.nih.gov/web_policies.html",
		attributionText: "U.S. National Library of Medicine UCUM service",
	},
	{
		key: "shared-catalog",
		displayName: "blendCalc verified catalog",
		sourceType: "internal_catalog",
		homepageUrl: null,
		apiBaseUrl: null,
		termsUrl: null,
		attributionText: "blendCalc community-reviewed catalog",
	},
];

export const SERVING_MEASURE_REQUESTS = [
	{
		key: "g",
		displayLabel: "grams (g)",
		shortLabel: "g",
		dimension: "weight",
		baseUnitKey: "g",
		standardsCode: "g",
		displayOrder: 10,
		isDefault: true,
		aliases: ["g", "gram", "grams"],
	},
	{
		key: "mg",
		displayLabel: "milligrams (mg)",
		shortLabel: "mg",
		dimension: "weight",
		baseUnitKey: "g",
		standardsCode: "10*-3.g",
		displayOrder: 20,
		isDefault: false,
		aliases: ["mg", "milligram", "milligrams"],
	},
	{
		key: "oz",
		displayLabel: "ounces (oz)",
		shortLabel: "oz",
		dimension: "weight",
		baseUnitKey: "g",
		standardsCode: "[oz_av]",
		displayOrder: 30,
		isDefault: false,
		aliases: ["oz", "ounce", "ounces"],
	},
	{
		key: "kg",
		displayLabel: "kilograms (kg)",
		shortLabel: "kg",
		dimension: "weight",
		baseUnitKey: "g",
		standardsCode: "kg",
		displayOrder: 40,
		isDefault: false,
		aliases: ["kg", "kilogram", "kilograms"],
	},
	{
		key: "lb",
		displayLabel: "pounds (lb)",
		shortLabel: "lb",
		dimension: "weight",
		baseUnitKey: "g",
		standardsCode: "[lb_av]",
		displayOrder: 50,
		isDefault: false,
		aliases: ["lb", "lbs", "pound", "pounds"],
	},
	{
		key: "ml",
		displayLabel: "milliliters (ml)",
		shortLabel: "ml",
		dimension: "volume",
		baseUnitKey: "ml",
		standardsCode: "mL",
		displayOrder: 60,
		isDefault: true,
		aliases: ["ml", "mlt", "milliliter", "milliliters", "millilitre", "millilitres"],
	},
	{
		key: "tsp",
		displayLabel: "teaspoons (tsp)",
		shortLabel: "tsp",
		dimension: "volume",
		baseUnitKey: "ml",
		standardsCode: "[tsp_us]",
		displayOrder: 70,
		isDefault: false,
		aliases: ["tsp", "teaspoon", "teaspoons"],
	},
	{
		key: "tbsp",
		displayLabel: "tablespoons (tbsp)",
		shortLabel: "tbsp",
		dimension: "volume",
		baseUnitKey: "ml",
		standardsCode: "[tbs_us]",
		displayOrder: 80,
		isDefault: false,
		aliases: ["tbsp", "tablespoon", "tablespoons"],
	},
	{
		key: "cup",
		displayLabel: "cups",
		shortLabel: "cup",
		dimension: "volume",
		baseUnitKey: "ml",
		standardsCode: "[cup_us]",
		displayOrder: 90,
		isDefault: false,
		aliases: ["c", "cup", "cups"],
	},
	{
		key: "floz",
		displayLabel: "fluid ounces (fl oz)",
		shortLabel: "fl oz",
		dimension: "volume",
		baseUnitKey: "ml",
		standardsCode: "[foz_us]",
		displayOrder: 100,
		isDefault: false,
		aliases: ["floz", "flounce", "flounces", "fluidounce", "fluidounces", "fl oz", "fluid ounce", "fluid ounces"],
	},
];

export const UNIT_STANDARDS_CODES = {
	G: "g",
	MG: "10*-3.g",
	UG: "10*-6.g",
	KCAL: "kcal",
	KJ: "kJ",
};
