<script lang="ts">
	import type { ManualEntryStepContentProps } from "./types";
	import IdentityStep from "$lib/components/ingredients/manual-entry/steps/IdentityStep/IdentityStep.svelte";
	import NutrientStep from "$lib/components/ingredients/manual-entry/steps/NutrientStep/NutrientStep.svelte";
	import ServingsStep from "$lib/components/ingredients/manual-entry/steps/ServingsStep/ServingsStep.svelte";
	import ShareStep from "$lib/components/ingredients/manual-entry/steps/ShareStep/ShareStep.svelte";

	let {
		activeStep,
		name,
		brandOwner,
		category,
		categoryOptionId,
		barcode,
		categoryWarningMessage,
		categorySourceValues,
		barcodeMessage,
		barcodeValidationMessage,
		checkingBarcodeReference,
		barcodeSuggestion,
		servingLabel,
		resolvedServingLabel,
		servingWeightGrams,
		useVolumeEquivalent,
		volumeQuantity,
		volumeUnit,
		volumeOptions,
		manualEntryNutrientGroups,
		loadingManualEntryNutrients,
		manualEntryNutrientError,
		nutritionLabelOcrMappings,
		nutritionLabelOcrMappingError,
		nutritionPhoto,
		hideMacroUnavailableStatus,
		customIngredientValidationItems,
		normalizedName,
		activeCategory,
		summaryNutrients,
		optionalNutrientCount,
		canShareWithCatalog,
		shareUnavailableMessage,
		shareHelpMessage,
		shareWithCatalog,
		barcodeShareMismatch,
		validatingBarcodeShare,
		requiresCatalogEvidence,
		showOptionalProductImageUpload,
		trustedProductImage,
		frontPhoto,
		imagePlacement,
		saveDestination,
		error,
		lastOutcome,
		outcomeAction,
		savedMessage,
		catalogMessage,
		saving,
		getAttemptedValidationItems,
		getManualNutrientValue,
		onValueChange,
		onApplyNutritionLabelOcr,
		isRequired,
		onNameChange,
		onBrandChange,
		onCategoryChange,
		onCategoryStatusChange,
		onBarcodeChange,
		onBarcodeBlur,
		onApplyBarcodeSuggestion,
		onKeepManualBarcodeEntry,
		onNameInput,
		onServingLabelChange,
		onServingWeightChange,
		onUseVolumeChange,
		onVolumeQuantityChange,
		onVolumeUnitChange,
		onShareChange,
		onApplyVerifiedBarcode,
		onDetachBarcodeForPrivateSave,
		onFrontPhotoChange,
		onImagePlacementChange,
		onNutritionPhotoChange,
		onBarcodePhotoChange,
		onSaveDestinationChange,
		onSaveDestinationInput,
		onMoveToShopping,
		onMoveToFridge,
		onUndo,
		onBack,
		onNext,
		onSubmit,
	}: ManualEntryStepContentProps = $props();
</script>

{#if activeStep === "identity"}
	<IdentityStep
		{name}
		{brandOwner}
		{category}
		{categoryOptionId}
		{barcode}
		{categoryWarningMessage}
		{categorySourceValues}
		{barcodeMessage}
		{barcodeValidationMessage}
		{checkingBarcodeReference}
		{barcodeSuggestion}
		onNameChange={onNameChange}
		onBrandChange={onBrandChange}
		onCategoryChange={onCategoryChange}
		onCategoryStatusChange={onCategoryStatusChange}
		onBarcodeChange={onBarcodeChange}
		onBarcodeBlur={onBarcodeBlur}
		onApplyBarcodeSuggestion={onApplyBarcodeSuggestion}
		onKeepManualBarcodeEntry={onKeepManualBarcodeEntry}
		onNameInput={onNameInput}
		onNext={onNext}
	/>
{:else if activeStep === "servings"}
	<ServingsStep
		{servingLabel}
		{resolvedServingLabel}
		{servingWeightGrams}
		{useVolumeEquivalent}
		{volumeQuantity}
		{volumeUnit}
		{volumeOptions}
		onServingLabelChange={onServingLabelChange}
		onServingWeightChange={onServingWeightChange}
		onUseVolumeChange={onUseVolumeChange}
		onVolumeQuantityChange={onVolumeQuantityChange}
		onVolumeUnitChange={onVolumeUnitChange}
		onBack={onBack}
		onNext={onNext}
	/>
{:else if activeStep === "macros"}
	<NutrientStep
		groups={manualEntryNutrientGroups.macros}
		loading={loadingManualEntryNutrients}
		error={manualEntryNutrientError}
		helper="Enter values from the nutrition label for the serving above. The app stores normalized per-100g values. Fields marked * are required."
		hideUnavailableStatus={hideMacroUnavailableStatus}
		validationItems={getAttemptedValidationItems(
			customIngredientValidationItems.filter((item) => item.step === "macros"),
		)}
		labelOcrMappings={nutritionLabelOcrMappings}
		labelOcrMappingError={nutritionLabelOcrMappingError}
		{nutritionPhoto}
		onNutritionPhotoChange={onNutritionPhotoChange}
		{onApplyNutritionLabelOcr}
		getValue={getManualNutrientValue}
		onValueChange={onValueChange}
		{isRequired}
		onBack={onBack}
		onNext={onNext}
	/>
{:else if activeStep === "extended"}
	<NutrientStep
		groups={manualEntryNutrientGroups.extended}
		loading={loadingManualEntryNutrients}
		error={manualEntryNutrientError}
		helper="All fields on this step are optional. Fill what you know."
		accordion
		defaultOpenFirst={false}
		getValue={getManualNutrientValue}
		onValueChange={onValueChange}
		{isRequired}
		onBack={onBack}
		onNext={onNext}
	/>
{:else}
	<ShareStep
		{normalizedName}
		{activeCategory}
		{summaryNutrients}
		{optionalNutrientCount}
		validationItems={getAttemptedValidationItems(customIngredientValidationItems)}
		{barcodeMessage}
		{canShareWithCatalog}
		{shareUnavailableMessage}
		{shareHelpMessage}
		{shareWithCatalog}
		{barcodeShareMismatch}
		{validatingBarcodeShare}
		{requiresCatalogEvidence}
		{showOptionalProductImageUpload}
		{trustedProductImage}
		{frontPhoto}
		{imagePlacement}
		{saveDestination}
		{error}
		{lastOutcome}
		{outcomeAction}
		{savedMessage}
		{catalogMessage}
		{saving}
		onShareChange={onShareChange}
		onApplyVerifiedBarcode={onApplyVerifiedBarcode}
		onDetachBarcodeForPrivateSave={onDetachBarcodeForPrivateSave}
		onFrontPhotoChange={onFrontPhotoChange}
		onImagePlacementChange={onImagePlacementChange}
		onNutritionPhotoChange={onNutritionPhotoChange}
		onBarcodePhotoChange={onBarcodePhotoChange}
		onSaveDestinationChange={onSaveDestinationChange}
		onSaveDestinationInput={onSaveDestinationInput}
		onMoveToShopping={onMoveToShopping}
		onMoveToFridge={onMoveToFridge}
		onUndo={onUndo}
		onBack={onBack}
		onSubmit={onSubmit}
	/>
{/if}
