/**
 * Purpose: Manage blendCalc's isolated local Supabase test stack, generate its
 * gitignored environment file, seed local-only QA accounts with deterministic
 * onboarding, list, Saved, Mix, preference, and moderation state, and run pgTAP
 * checks. Personas cover populated, warning-heavy, empty, guided-tour, moderator,
 * and admin workflows. Rerunning start repairs missing baseline fixtures without
 * moving existing list items; reset recreates the exact documented baseline.
 * Run: `npm run db:test:start`, `npm run db:test:reset`,
 * `npm run db:test:verify`, `npm run db:test:status`, or `npm run db:test:stop`.
 * Reset and verify are destructive only to the localhost database and never use the
 * linked remote project.
 */

import { spawnSync } from "node:child_process";
import { randomUUID } from "node:crypto";
import { readFile, readdir, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { createClient } from "@supabase/supabase-js";
import WebSocket from "ws";
import {
	getLocalQaCatalogBarcodes,
	localQaPersonas,
	localQaSavedDrinks,
} from "../lib/local_qa_personas.mjs";

const repositoryRoot = fileURLToPath(new URL("../..", import.meta.url));
const testEnvironmentPath = fileURLToPath(
	new URL("../../.env.test.local", import.meta.url),
);
const supabaseConfigPath = fileURLToPath(
	new URL("../../supabase/config.toml", import.meta.url),
);
const testSeedPath = fileURLToPath(
	new URL("../../supabase/seed.sql", import.meta.url),
);
const databaseTestDirectory = new URL(
	"../../supabase/tests/database/",
	import.meta.url,
);
const action = process.argv[2] ?? "status";
const serviceReadinessAttempts = 30;
const serviceReadinessDelayMs = 1000;
const currentTutorialVersion = 3;

const testAccounts = localQaPersonas;

const runCommand = (command, args, { capture = false, input } = {}) => {
	const shouldPipe = capture || input !== undefined;
	const result = spawnSync(command, args, {
		cwd: repositoryRoot,
		encoding: "utf8",
		input,
		stdio: shouldPipe ? ["pipe", "pipe", "pipe"] : "inherit",
	});

	if (result.status !== 0) {
		const detail = [result.stdout, result.stderr].filter(Boolean).join("\n").trim();
		throw new Error(
			`${command} ${args.join(" ")} failed${detail ? `:\n${detail}` : "."}`,
		);
	}

	return result.stdout ?? "";
};

const commandSucceeds = (command, args) =>
	spawnSync(command, args, {
		cwd: repositoryRoot,
		stdio: "ignore",
	}).status === 0;

const ensureContainerRuntime = () => {
	if (commandSucceeds("docker", ["info"])) return;

	if (commandSucceeds("colima", ["version"])) {
		runCommand("colima", [
			"start",
			"--cpu",
			"4",
			"--memory",
			"8",
			"--disk",
			"40",
		]);
	}

	if (!commandSucceeds("docker", ["info"])) {
		throw new Error(
			"A Docker-compatible runtime is required. Install Docker and Colima, then rerun the command.",
		);
	}
};

const parseStatusEnvironment = (output) => {
	const values = {};
	for (const line of output.split("\n")) {
		const match = line.match(/^([A-Z][A-Z0-9_]*)=(.*)$/);
		if (!match) continue;
		let value = match[2].trim();
		if (value.startsWith('"') && value.endsWith('"')) {
			value = JSON.parse(value);
		}
		values[match[1]] = value;
	}
	return values;
};

const getLocalEnvironment = () => {
	const values = parseStatusEnvironment(
		runCommand("supabase", ["status", "-o", "env"], { capture: true }),
	);
	const apiUrl = values.API_URL;
	const publishableKey = values.PUBLISHABLE_KEY ?? values.ANON_KEY;
	const serviceRoleKey = values.SERVICE_ROLE_KEY ?? values.SECRET_KEY;

	if (!apiUrl || !publishableKey || !serviceRoleKey) {
		throw new Error("The local Supabase status did not provide the required API keys.");
	}

	const hostname = new URL(apiUrl).hostname;
	if (hostname !== "127.0.0.1" && hostname !== "localhost") {
		throw new Error(`Refusing to treat non-local Supabase URL ${apiUrl} as a test database.`);
	}

	return { apiUrl, publishableKey, serviceRoleKey };
};

const writeTestEnvironment = async (environment) => {
	const accountByKey = new Map(testAccounts.map((account) => [account.key, account]));
	const lines = [
		"# Generated by npm run db:test:start. Do not commit this file.",
		`PUBLIC_SUPABASE_URL=${JSON.stringify(environment.apiUrl)}`,
		`PUBLIC_SUPABASE_PUBLISHABLE_KEY=${JSON.stringify(environment.publishableKey)}`,
		`SUPABASE_SERVICE_ROLE_KEY=${JSON.stringify(environment.serviceRoleKey)}`,
		`BLENDCALC_TEST_USER_EMAIL=${JSON.stringify(accountByKey.get("user").email)}`,
		`BLENDCALC_TEST_PREFERENCES_EMAIL=${JSON.stringify(accountByKey.get("preferences").email)}`,
		`BLENDCALC_TEST_EMPTY_EMAIL=${JSON.stringify(accountByKey.get("empty").email)}`,
		`BLENDCALC_TEST_ONBOARDING_EMAIL=${JSON.stringify(accountByKey.get("onboarding").email)}`,
		`BLENDCALC_TEST_MODERATOR_EMAIL=${JSON.stringify(accountByKey.get("moderator").email)}`,
		`BLENDCALC_TEST_ADMIN_EMAIL=${JSON.stringify(accountByKey.get("admin").email)}`,
		`BLENDCALC_TEST_ACCOUNT_PASSWORD=${JSON.stringify(testAccounts[0].password)}`,
		"",
	];
	await writeFile(testEnvironmentPath, lines.join("\n"), { mode: 0o600 });
};

const readLocalProjectId = async () => {
	const config = await readFile(supabaseConfigPath, "utf8");
	const projectId = config.match(/^project_id\s*=\s*"([^"]+)"$/m)?.[1];
	if (!projectId) {
		throw new Error("Unable to determine the local Supabase project ID.");
	}
	return projectId;
};

const getLocalServiceContainer = async (serviceName) => {
	const projectId = await readLocalProjectId();
	const containers = runCommand(
		"docker",
		[
			"ps",
			"--filter",
			`label=com.supabase.cli.project=${projectId}`,
			"--filter",
			`name=supabase_${serviceName}_`,
			"--format",
			"{{.Names}}",
		],
		{ capture: true },
	)
		.trim()
		.split("\n")
		.filter(Boolean);

	if (containers.length !== 1) {
		throw new Error(
			`Expected one local Supabase ${serviceName} container for ${projectId}, found ${containers.length}.`,
		);
	}

	return containers[0];
};

const applyLocalQaSeed = async () => {
	const databaseContainer = await getLocalServiceContainer("db");
	const seedSql = await readFile(testSeedPath, "utf8");
	console.log("Applying deterministic local QA reference fixtures...");
	runCommand(
		"docker",
		[
			"exec",
			"-i",
			databaseContainer,
			"psql",
			"--set",
			"ON_ERROR_STOP=1",
			"--username",
			"postgres",
			"--dbname",
			"postgres",
		],
		{ capture: true, input: seedSql },
	);
};

const restartLocalGateway = async () => {
	const gatewayContainer = await getLocalServiceContainer("kong");
	console.log("Refreshing the local Supabase gateway...");
	runCommand("docker", ["restart", gatewayContainer], { capture: true });
};

const collectDatabaseTestFiles = async (directory) => {
	const entries = await readdir(directory, { withFileTypes: true });
	const files = [];
	for (const entry of entries) {
		const entryUrl = new URL(entry.name, directory);
		if (entry.isDirectory()) {
			entryUrl.pathname += "/";
			files.push(...await collectDatabaseTestFiles(entryUrl));
		} else if (entry.isFile() && entry.name.endsWith(".sql")) {
			files.push(entryUrl);
		}
	}
	return files.sort((left, right) => left.pathname.localeCompare(right.pathname));
};

const runDatabaseTests = async () => {
	const databaseContainer = await getLocalServiceContainer("db");
	const testFiles = await collectDatabaseTestFiles(databaseTestDirectory);
	if (testFiles.length === 0) {
		throw new Error("No pgTAP database tests were found.");
	}

	runCommand(
		"docker",
		[
			"exec",
			databaseContainer,
			"psql",
			"--set",
			"ON_ERROR_STOP=1",
			"--username",
			"postgres",
			"--dbname",
			"postgres",
			"--command",
			"create extension if not exists pgtap with schema extensions",
		],
		{ capture: true },
	);

	for (const testFile of testFiles) {
		const testSql = await readFile(testFile, "utf8");
		const output = runCommand(
			"docker",
			[
				"exec",
				"--env",
				"PGOPTIONS=--search_path=public,extensions",
				"--interactive",
				databaseContainer,
				"psql",
				"--set",
				"ON_ERROR_STOP=1",
				"--username",
				"postgres",
				"--dbname",
				"postgres",
				"--tuples-only",
				"--no-align",
			],
			{ capture: true, input: testSql },
		);
		if (!/^1\.\.\d+$/m.test(output) || /^not ok\b/m.test(output)) {
			throw new Error(
				`Database test ${fileURLToPath(testFile)} failed:\n${output.trim()}`,
			);
		}
		console.log(output.trim());
	}
};

const requireSuccessfulResult = (result, label) => {
	if (result.error) throw new Error(`${label}: ${result.error.message}`);
	return result.data;
};

const loadTestCatalogFoods = async (admin) => {
	const expectedBarcodes = getLocalQaCatalogBarcodes();
	const products = requireSuccessfulResult(
		await admin
			.from("shared_products")
			.select("id, barcode, confidence, food")
			.in("barcode", expectedBarcodes)
			.eq("status", "active"),
		"Load local QA catalog products for account personas",
	);
	const productsByBarcode = new Map(
		products.map((product) => {
			const food = {
				...product.food,
				customFood: false,
				sharedProductId: product.id,
				sharedProductConfidence: product.confidence,
			};
			if (!Number.isSafeInteger(Number(food.fdcId))) {
				throw new Error(
					`Local QA catalog product ${product.barcode} has no valid food identity.`,
				);
			}
			return [product.barcode, food];
		}),
	);

	for (const barcode of expectedBarcodes) {
		if (!productsByBarcode.has(barcode)) {
			throw new Error(
				`Local QA catalog product ${barcode} is unavailable for persona seeding.`,
			);
		}
	}

	return productsByBarcode;
};

const wait = (milliseconds) =>
	new Promise((resolve) => {
		setTimeout(resolve, milliseconds);
	});

const formatSupabaseError = (error) => {
	if (!error) return "Unknown service error.";
	if (typeof error.message === "string" && error.message.trim()) {
		return error.message;
	}
	try {
		return JSON.stringify(error);
	} catch {
		return String(error);
	}
};

const waitForLocalServices = async (admin) => {
	let lastAuthError;
	let lastDatabaseError;

	for (let attempt = 1; attempt <= serviceReadinessAttempts; attempt += 1) {
		const [usersResult, profilesResult] = await Promise.all([
			admin.auth.admin.listUsers({ page: 1, perPage: 1000 }),
			admin.from("profiles").select("user_id").limit(1),
		]);

		if (!usersResult.error && !profilesResult.error) {
			return usersResult.data;
		}

		lastAuthError = usersResult.error;
		lastDatabaseError = profilesResult.error;
		if (attempt < serviceReadinessAttempts) {
			await wait(serviceReadinessDelayMs);
		}
	}

	throw new Error(
		[
			"Local Supabase services did not become ready before QA account seeding.",
			`Auth: ${formatSupabaseError(lastAuthError)}`,
			`Database: ${formatSupabaseError(lastDatabaseError)}`,
		].join(" "),
	);
};

const qaNutrientOptions = [
	{ id: 1008, label: "Calories" },
	{ id: 1003, label: "Protein" },
	{ id: 1079, label: "Dietary Fiber" },
	{ id: 1005, label: "Total Carbohydrates" },
	{ id: 1004, label: "Total Fat" },
];

const requireCatalogFood = (catalogFoods, barcode) => {
	const food = catalogFoods.get(barcode);
	if (!food) {
		throw new Error(`Local QA food ${barcode} is unavailable.`);
	}
	return food;
};

const seedTestFoodLists = async (userClient, account, catalogFoods) => {
	for (const listType of ["fridge", "shopping"]) {
		const foods = account.lists[listType].map((barcode) =>
			requireCatalogFood(catalogFoods, barcode),
		);
		if (foods.length === 0) continue;
		const result = requireSuccessfulResult(
			await userClient.rpc("place_user_food_list_items", {
				p_foods: foods,
				p_list_type: listType,
			}),
			`Seed ${listType} ingredients for ${account.email}`,
		);
		if (result !== "added" && result !== "duplicate") {
			throw new Error(
				`Unexpected ${listType} fixture result for ${account.email}: ${result}.`,
			);
		}
	}
};

const createSavedDrink = (definition, catalogFoods, id = randomUUID()) => {
	const foods = definition.ingredients.map(([barcode]) =>
		requireCatalogFood(catalogFoods, barcode),
	);
	const servingGrams = Object.fromEntries(
		definition.ingredients.map(([barcode, grams]) => [
			requireCatalogFood(catalogFoods, barcode).fdcId,
			grams,
		]),
	);
	const servingQuantities = { ...servingGrams };
	const servingUnits = Object.fromEntries(
		foods.map((food) => [food.fdcId, "g"]),
	);

	return {
		id,
		name: definition.name,
		createdAt: new Date(definition.createdAt).getTime(),
		foods,
		selected: qaNutrientOptions.map(({ id: nutrientId }) => nutrientId),
		options: qaNutrientOptions,
		nutrientGoals: definition.goals,
		servingGrams,
		servingQuantities,
		servingUnits,
	};
};

const seedTestSavedDrinks = async (userClient, account, catalogFoods) => {
	if (account.savedDrinkKeys.length === 0) return;
	const existingRows = requireSuccessfulResult(
		await userClient.from("saved_drinks").select("id, name"),
		`Load saved mixes for ${account.email}`,
	);
	const existingIdsByName = new Map(
		existingRows.map((row) => [row.name.toLowerCase(), row.id]),
	);

	for (const savedDrinkKey of account.savedDrinkKeys) {
		const definition = localQaSavedDrinks[savedDrinkKey];
		const drink = createSavedDrink(
			definition,
			catalogFoods,
			existingIdsByName.get(definition.name.toLowerCase()) ?? randomUUID(),
		);
		const result = requireSuccessfulResult(
			await userClient.rpc("save_saved_drink", {
				p_created_at: new Date(drink.createdAt).toISOString(),
				p_drink: drink,
				p_id: drink.id,
				p_name: drink.name,
			}),
			`Seed saved mix ${drink.name} for ${account.email}`,
		);
		if (result !== "saved" && result !== "duplicate") {
			throw new Error(
				`Unexpected saved mix result for ${account.email}: ${result}.`,
			);
		}
	}
};

const seedTestMixPreferences = async (userClient, account, catalogFoods) => {
	if (!account.activeMixKey) return;
	const definition = localQaSavedDrinks[account.activeMixKey];
	const drink = createSavedDrink(definition, catalogFoods);
	const result = requireSuccessfulResult(
		await userClient.rpc("save_mix_preferences", {
			p_nutrient_goals: drink.nutrientGoals,
			p_mix_state: {
				version: 1,
				selected: drink.selected,
				options: drink.options,
				selectedFoodIds: drink.foods.map((food) => food.fdcId),
				servingGrams: drink.servingGrams,
				servingQuantities: drink.servingQuantities,
				servingUnits: drink.servingUnits,
			},
		}),
		`Seed Mix state for ${account.email}`,
	);
	if (result !== true) {
		throw new Error(`Mix state could not be seeded for ${account.email}.`);
	}
};

const seedTestFoodPreferences = async (userClient, account, userId) => {
	if (!account.preferences) return;
	requireSuccessfulResult(
		await userClient.from("user_food_preferences").upsert(
			{
				user_id: userId,
				...account.preferences,
				sensitive_acknowledged_at: "2026-08-01T00:00:00.000Z",
			},
			{ onConflict: "user_id" },
		),
		`Seed food preferences for ${account.email}`,
	);
};

const seedTestAccountState = async (
	environment,
	account,
	expectedUserId,
	catalogFoods,
) => {
	const userClient = createClient(
		environment.apiUrl,
		environment.publishableKey,
		{
			auth: {
				autoRefreshToken: false,
				detectSessionInUrl: false,
				persistSession: false,
			},
			realtime: { transport: WebSocket },
		},
	);
	const session = requireSuccessfulResult(
		await userClient.auth.signInWithPassword({
			email: account.email,
			password: account.password,
		}),
		`Sign in ${account.email} for tutorial setup`,
	);
	if (session.user.id !== expectedUserId) {
		throw new Error(`Tutorial setup resolved the wrong user for ${account.email}.`);
	}

	if (account.tutorialState === "pending") {
		requireSuccessfulResult(
			await userClient.from("user_tutorial_preferences").upsert(
				{
					user_id: expectedUserId,
					tutorial_version: currentTutorialVersion,
					do_not_show_again: false,
					remind_after: null,
					last_seen_at: "2026-07-01T00:00:00.000Z",
					completed_at: null,
				},
				{ onConflict: "user_id" },
			),
			`Seed guided tour for ${account.email}`,
		);
	} else {
		const tutorialCompletedAt = "2026-08-01T00:00:00.000Z";
		requireSuccessfulResult(
			await userClient.from("user_tutorial_preferences").upsert(
				{
					user_id: expectedUserId,
					tutorial_version: currentTutorialVersion,
					do_not_show_again: true,
					remind_after: null,
					last_seen_at: tutorialCompletedAt,
					completed_at: tutorialCompletedAt,
				},
				{ onConflict: "user_id" },
			),
			`Seed tutorial preference for ${account.email}`,
		);
	}

	await seedTestFoodLists(userClient, account, catalogFoods);
	await seedTestSavedDrinks(userClient, account, catalogFoods);
	await seedTestMixPreferences(userClient, account, catalogFoods);
	await seedTestFoodPreferences(userClient, account, expectedUserId);
	await userClient.auth.signOut();
};

const createModerationFood = (barcode, description, fdcId) => ({
	fdcId,
	description,
	nameProvenance: "user",
	brandOwner: "blendCalc QA Kitchen",
	foodCategory: "Snacks",
	categoryOptionId: "qa-snacks",
	dataType: "Custom Food",
	foodIdentityType: "packaged",
	servingSize: 28,
	servingSizeUnit: "g",
	householdServingFullText: "About 12 crisps (28 g)",
	hasSourceServing: true,
	foodServings: [{
		label: "About 12 crisps (28 g)",
		gramWeight: 28,
		isPrimary: true,
		measureType: "Package serving",
		isHouseholdMeasure: true,
		sourceMeasureKey: "qa-package-serving",
		origin: "package-label",
		gramWeightMethod: "source-reported",
	}],
	gtinUpc: barcode,
	barcode,
	barcodeSource: "manual",
	customFood: true,
	ingredients: "Potatoes, sunflower oil, sea salt.",
	ingredientList: ["Potatoes", "Sunflower oil", "Sea salt"],
	allergens: [],
	traces: [],
	dietaryTags: ["vegan", "vegetarian"],
	reportedNutrientIds: [1008, 1004, 1005, 1079, 2000, 1003, 1093],
	foodNutrients: [
		{ nutrientId: 1008, nutrientName: "Energy", nutrientNumber: "208", unitName: "KCAL", value: 536, valueOrigin: "reported", valueStatus: "reported", mappingStatus: "canonical" },
		{ nutrientId: 1004, nutrientName: "Total lipid (fat)", nutrientNumber: "204", unitName: "G", value: 32.1, valueOrigin: "reported", valueStatus: "reported", mappingStatus: "canonical" },
		{ nutrientId: 1005, nutrientName: "Carbohydrate, by difference", nutrientNumber: "205", unitName: "G", value: 57.1, valueOrigin: "reported", valueStatus: "reported", mappingStatus: "canonical" },
		{ nutrientId: 1079, nutrientName: "Fiber, total dietary", nutrientNumber: "291", unitName: "G", value: 3.6, valueOrigin: "reported", valueStatus: "reported", mappingStatus: "canonical" },
		{ nutrientId: 2000, nutrientName: "Sugars, total including NLEA", nutrientNumber: "269", unitName: "G", value: 3.6, valueOrigin: "reported", valueStatus: "reported", mappingStatus: "canonical" },
		{ nutrientId: 1003, nutrientName: "Protein", nutrientNumber: "203", unitName: "G", value: 7.1, valueOrigin: "reported", valueStatus: "reported", mappingStatus: "canonical" },
		{ nutrientId: 1093, nutrientName: "Sodium, Na", nutrientNumber: "307", unitName: "MG", value: 643, valueOrigin: "reported", valueStatus: "reported", mappingStatus: "canonical" },
	],
});

const seedModerationFixtures = async (admin, submittingUserId) => {
	if (!submittingUserId) {
		throw new Error("The populated QA user is unavailable for moderation fixtures.");
	}

	const completeSubmissionId = "83000000-0000-4000-8000-000000000001";
	const incompleteSubmissionId = "83000000-0000-4000-8000-000000000002";
	const completeEvidencePaths = Object.fromEntries(
		["front", "nutrition", "barcode"].map((role) => [
			role,
			`${submittingUserId}/qa-catalog-review/${role}.png`,
		]),
	);
	const evidenceImage = await readFile(
		new URL("../../static/og-image.png", import.meta.url),
	);
	for (const path of Object.values(completeEvidencePaths)) {
		requireSuccessfulResult(
			await admin.storage
				.from("product-submission-evidence")
				.upload(path, evidenceImage, {
					contentType: "image/png",
					upsert: true,
				}),
			`Seed moderation evidence ${path}`,
		);
	}

	const existingSubmissions = requireSuccessfulResult(
		await admin
			.from("shared_product_submissions")
			.select("id")
			.in("id", [completeSubmissionId, incompleteSubmissionId]),
		"Load local QA moderation fixtures",
	);
	const existingIds = new Set(existingSubmissions.map(({ id }) => id));
	const submissions = [
		{
			id: completeSubmissionId,
			barcode: "09999000000008",
			product_name: "QA Reviewable Pantry Crisps",
			food: createModerationFood(
				"09999000000008",
				"QA Reviewable Pantry Crisps",
				-9900001,
			),
			evidence_paths: completeEvidencePaths,
			evidence_complete: true,
			validation_report: {
				valid: false,
				issues: ["QA fixture: review the supplied package evidence."],
				evidenceComplete: true,
				externalLookupFailed: true,
				conflictCount: 1,
				qaSeed: true,
			},
		},
		{
			id: incompleteSubmissionId,
			barcode: "09999000000015",
			product_name: "QA Missing Evidence Pantry Crisps",
			food: createModerationFood(
				"09999000000015",
				"QA Missing Evidence Pantry Crisps",
				-9900002,
			),
			evidence_paths: {},
			evidence_complete: false,
			validation_report: {
				valid: false,
				issues: ["QA fixture: required package evidence is intentionally missing."],
				evidenceComplete: false,
				externalLookupFailed: true,
				conflictCount: 0,
				qaSeed: true,
			},
		},
	]
		.filter(({ id }) => !existingIds.has(id))
		.map((submission) => ({
			...submission,
			submitted_by: submittingUserId,
			brand_owner: "blendCalc QA Kitchen",
			category_option_id: "qa-snacks",
			consent_to_share: true,
			status: "pending",
			verification_status: "manual_review",
			matched_source: null,
			matched_reference: null,
		}));

	if (submissions.length > 0) {
		requireSuccessfulResult(
			await admin.from("shared_product_submissions").insert(submissions),
			"Seed local QA moderation queue",
		);
	}
};

const seedTestAccounts = async (environment) => {
	const admin = createClient(environment.apiUrl, environment.serviceRoleKey, {
		auth: {
			autoRefreshToken: false,
			detectSessionInUrl: false,
			persistSession: false,
		},
		realtime: { transport: WebSocket },
	});
	const listedUsers = await waitForLocalServices(admin);
	const catalogFoods = await loadTestCatalogFoods(admin);
	const usersByEmail = new Map(
		listedUsers.users.map((user) => [user.email?.toLowerCase(), user]),
	);
	const userIdsByPersonaKey = new Map();

	for (const account of testAccounts) {
		let user = usersByEmail.get(account.email);
		if (user) {
			user = requireSuccessfulResult(
				await admin.auth.admin.updateUserById(user.id, {
					password: account.password,
					user_metadata: { display_name: account.displayName },
				}),
				`Update ${account.email}`,
			).user;
		} else {
			user = requireSuccessfulResult(
				await admin.auth.admin.createUser({
					email: account.email,
					password: account.password,
					email_confirm: true,
					user_metadata: { display_name: account.displayName },
				}),
				`Create ${account.email}`,
			).user;
		}

		requireSuccessfulResult(
			await admin.from("profiles").upsert(
				{
					user_id: user.id,
					display_name: account.displayName,
				},
				{ onConflict: "user_id" },
			),
			`Seed profile for ${account.email}`,
		);

		requireSuccessfulResult(
			await admin.rpc("set_app_user_role", {
				p_target_user_id: user.id,
				p_role: account.role,
				p_actor_user_id: null,
				p_reason_code: "local_test_fixture",
				p_internal_note: "Seeded by the isolated local test database manager.",
			}),
			`Seed role for ${account.email}`,
		);

		await seedTestAccountState(
			environment,
			account,
			user.id,
			catalogFoods,
		);
		userIdsByPersonaKey.set(account.key, user.id);
	}

	await seedModerationFixtures(admin, userIdsByPersonaKey.get("user"));
};

const startLocalStack = async ({
	seedAccounts = true,
	applyMigrations = true,
	applyReferenceFixtures = true,
} = {}) => {
	ensureContainerRuntime();
	console.log("Starting isolated local Supabase test stack...");
	runCommand("supabase", [
		"start",
		"--exclude",
		"edge-runtime,logflare,vector",
	], { capture: true });
	if (applyMigrations) {
		console.log("Applying pending local database migrations...");
		runCommand("supabase", ["migration", "up", "--local"]);
	}
	if (applyReferenceFixtures) await applyLocalQaSeed();
	const environment = getLocalEnvironment();
	await writeTestEnvironment(environment);
	if (seedAccounts) await seedTestAccounts(environment);
	return environment;
};

const resetLocalStack = async () => {
	await startLocalStack({
		seedAccounts: false,
		applyMigrations: false,
		applyReferenceFixtures: false,
	});
	runCommand("supabase", ["db", "reset", "--local"]);
	await restartLocalGateway();
	await applyLocalQaSeed();
	const environment = getLocalEnvironment();
	await writeTestEnvironment(environment);
	await seedTestAccounts(environment);
};

const printAccounts = () => {
	console.log("Local QA accounts:");
	for (const account of testAccounts) {
		console.log(`- ${account.email} (${account.role}): ${account.purpose}`);
	}
	console.log(`- Password: ${testAccounts[0].password}`);
};

const main = async () => {
	switch (action) {
		case "start":
			await startLocalStack();
			printAccounts();
			break;
		case "reset":
			await resetLocalStack();
			printAccounts();
			break;
		case "verify":
			await resetLocalStack();
			await runDatabaseTests();
			printAccounts();
			break;
		case "status":
			ensureContainerRuntime();
			{
				const values = parseStatusEnvironment(
					runCommand("supabase", ["status", "-o", "env"], { capture: true }),
				);
				console.log(`Local API: ${values.API_URL ?? "unavailable"}`);
				console.log(`Local Studio: ${values.STUDIO_URL ?? "unavailable"}`);
				console.log(`Test environment: ${testEnvironmentPath}`);
			}
			break;
		case "stop":
			ensureContainerRuntime();
			runCommand("supabase", ["stop"]);
			break;
		default:
			throw new Error(`Unknown test database action: ${action}`);
	}
};

main().catch((error) => {
	console.error(error instanceof Error ? error.message : error);
	process.exitCode = 1;
});
