/**
 * Purpose: Manage blendCalc's isolated local Supabase test stack, generate its
 * gitignored environment file, seed local-only QA accounts with deterministic
 * onboarding state, and run pgTAP checks.
 * Run: `npm run db:test:start`, `npm run db:test:reset`,
 * `npm run db:test:verify`, `npm run db:test:status`, or `npm run db:test:stop`.
 * Reset and verify are destructive only to the localhost database and never use the
 * linked remote project.
 */

import { spawnSync } from "node:child_process";
import { readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { createClient } from "@supabase/supabase-js";
import WebSocket from "ws";

const repositoryRoot = fileURLToPath(new URL("../..", import.meta.url));
const testEnvironmentPath = fileURLToPath(
	new URL("../../.env.test.local", import.meta.url),
);
const supabaseConfigPath = fileURLToPath(
	new URL("../../supabase/config.toml", import.meta.url),
);
const testSeedPath = fileURLToPath(
	new URL("../../supabase/seed.sql", import.meta.url),
);
const action = process.argv[2] ?? "status";
const serviceReadinessAttempts = 30;
const serviceReadinessDelayMs = 1000;
const currentTutorialVersion = 1;

const testAccounts = [
	{
		email: "qa-user@blendcalc.local",
		password: "BlendCalc-Local-QA-2026!",
		displayName: "QA User",
		role: null,
	},
	{
		email: "qa-moderator@blendcalc.local",
		password: "BlendCalc-Local-QA-2026!",
		displayName: "QA Moderator",
		role: "moderator",
	},
	{
		email: "qa-admin@blendcalc.local",
		password: "BlendCalc-Local-QA-2026!",
		displayName: "QA Admin",
		role: "admin",
	},
];

const runCommand = (command, args, { capture = false, input } = {}) => {
	const shouldPipe = capture || input !== undefined;
	const result = spawnSync(command, args, {
		cwd: repositoryRoot,
		encoding: "utf8",
		input,
		stdio: shouldPipe ? ["pipe", "pipe", "pipe"] : "inherit",
	});

	if (result.status !== 0) {
		const detail = [result.stdout, result.stderr].filter(Boolean).join("\n").trim();
		throw new Error(
			`${command} ${args.join(" ")} failed${detail ? `:\n${detail}` : "."}`,
		);
	}

	return result.stdout ?? "";
};

const commandSucceeds = (command, args) =>
	spawnSync(command, args, {
		cwd: repositoryRoot,
		stdio: "ignore",
	}).status === 0;

const ensureContainerRuntime = () => {
	if (commandSucceeds("docker", ["info"])) return;

	if (commandSucceeds("colima", ["version"])) {
		runCommand("colima", [
			"start",
			"--cpu",
			"4",
			"--memory",
			"8",
			"--disk",
			"40",
		]);
	}

	if (!commandSucceeds("docker", ["info"])) {
		throw new Error(
			"A Docker-compatible runtime is required. Install Docker and Colima, then rerun the command.",
		);
	}
};

const parseStatusEnvironment = (output) => {
	const values = {};
	for (const line of output.split("\n")) {
		const match = line.match(/^([A-Z][A-Z0-9_]*)=(.*)$/);
		if (!match) continue;
		let value = match[2].trim();
		if (value.startsWith('"') && value.endsWith('"')) {
			value = JSON.parse(value);
		}
		values[match[1]] = value;
	}
	return values;
};

const getLocalEnvironment = () => {
	const values = parseStatusEnvironment(
		runCommand("supabase", ["status", "-o", "env"], { capture: true }),
	);
	const apiUrl = values.API_URL;
	const publishableKey = values.PUBLISHABLE_KEY ?? values.ANON_KEY;
	const serviceRoleKey = values.SERVICE_ROLE_KEY ?? values.SECRET_KEY;

	if (!apiUrl || !publishableKey || !serviceRoleKey) {
		throw new Error("The local Supabase status did not provide the required API keys.");
	}

	const hostname = new URL(apiUrl).hostname;
	if (hostname !== "127.0.0.1" && hostname !== "localhost") {
		throw new Error(`Refusing to treat non-local Supabase URL ${apiUrl} as a test database.`);
	}

	return { apiUrl, publishableKey, serviceRoleKey };
};

const writeTestEnvironment = async (environment) => {
	const lines = [
		"# Generated by npm run db:test:start. Do not commit this file.",
		`PUBLIC_SUPABASE_URL=${JSON.stringify(environment.apiUrl)}`,
		`PUBLIC_SUPABASE_PUBLISHABLE_KEY=${JSON.stringify(environment.publishableKey)}`,
		`SUPABASE_SERVICE_ROLE_KEY=${JSON.stringify(environment.serviceRoleKey)}`,
		`BLENDCALC_TEST_USER_EMAIL=${JSON.stringify(testAccounts[0].email)}`,
		`BLENDCALC_TEST_MODERATOR_EMAIL=${JSON.stringify(testAccounts[1].email)}`,
		`BLENDCALC_TEST_ADMIN_EMAIL=${JSON.stringify(testAccounts[2].email)}`,
		`BLENDCALC_TEST_ACCOUNT_PASSWORD=${JSON.stringify(testAccounts[0].password)}`,
		"",
	];
	await writeFile(testEnvironmentPath, lines.join("\n"), { mode: 0o600 });
};

const readLocalProjectId = async () => {
	const config = await readFile(supabaseConfigPath, "utf8");
	const projectId = config.match(/^project_id\s*=\s*"([^"]+)"$/m)?.[1];
	if (!projectId) {
		throw new Error("Unable to determine the local Supabase project ID.");
	}
	return projectId;
};

const getLocalServiceContainer = async (serviceName) => {
	const projectId = await readLocalProjectId();
	const containers = runCommand(
		"docker",
		[
			"ps",
			"--filter",
			`label=com.supabase.cli.project=${projectId}`,
			"--filter",
			`name=supabase_${serviceName}_`,
			"--format",
			"{{.Names}}",
		],
		{ capture: true },
	)
		.trim()
		.split("\n")
		.filter(Boolean);

	if (containers.length !== 1) {
		throw new Error(
			`Expected one local Supabase ${serviceName} container for ${projectId}, found ${containers.length}.`,
		);
	}

	return containers[0];
};

const applyLocalQaSeed = async () => {
	const databaseContainer = await getLocalServiceContainer("db");
	const seedSql = await readFile(testSeedPath, "utf8");
	console.log("Applying deterministic local QA reference fixtures...");
	runCommand(
		"docker",
		[
			"exec",
			"-i",
			databaseContainer,
			"psql",
			"--set",
			"ON_ERROR_STOP=1",
			"--username",
			"postgres",
			"--dbname",
			"postgres",
		],
		{ capture: true, input: seedSql },
	);
};

const restartLocalGateway = async () => {
	const gatewayContainer = await getLocalServiceContainer("kong");
	console.log("Refreshing the local Supabase gateway...");
	runCommand("docker", ["restart", gatewayContainer], { capture: true });
};

const requireSuccessfulResult = (result, label) => {
	if (result.error) throw new Error(`${label}: ${result.error.message}`);
	return result.data;
};

const wait = (milliseconds) =>
	new Promise((resolve) => {
		setTimeout(resolve, milliseconds);
	});

const formatSupabaseError = (error) => {
	if (!error) return "Unknown service error.";
	if (typeof error.message === "string" && error.message.trim()) {
		return error.message;
	}
	try {
		return JSON.stringify(error);
	} catch {
		return String(error);
	}
};

const waitForLocalServices = async (admin) => {
	let lastAuthError;
	let lastDatabaseError;

	for (let attempt = 1; attempt <= serviceReadinessAttempts; attempt += 1) {
		const [usersResult, profilesResult] = await Promise.all([
			admin.auth.admin.listUsers({ page: 1, perPage: 1000 }),
			admin.from("profiles").select("user_id").limit(1),
		]);

		if (!usersResult.error && !profilesResult.error) {
			return usersResult.data;
		}

		lastAuthError = usersResult.error;
		lastDatabaseError = profilesResult.error;
		if (attempt < serviceReadinessAttempts) {
			await wait(serviceReadinessDelayMs);
		}
	}

	throw new Error(
		[
			"Local Supabase services did not become ready before QA account seeding.",
			`Auth: ${formatSupabaseError(lastAuthError)}`,
			`Database: ${formatSupabaseError(lastDatabaseError)}`,
		].join(" "),
	);
};

const seedTestTutorialPreference = async (
	environment,
	account,
	expectedUserId,
) => {
	const userClient = createClient(
		environment.apiUrl,
		environment.publishableKey,
		{
			auth: {
				autoRefreshToken: false,
				detectSessionInUrl: false,
				persistSession: false,
			},
			realtime: { transport: WebSocket },
		},
	);
	const session = requireSuccessfulResult(
		await userClient.auth.signInWithPassword({
			email: account.email,
			password: account.password,
		}),
		`Sign in ${account.email} for tutorial setup`,
	);
	if (session.user.id !== expectedUserId) {
		throw new Error(`Tutorial setup resolved the wrong user for ${account.email}.`);
	}

	const tutorialCompletedAt = new Date().toISOString();
	requireSuccessfulResult(
		await userClient.from("user_tutorial_preferences").upsert(
			{
				user_id: expectedUserId,
				tutorial_version: currentTutorialVersion,
				do_not_show_again: true,
				remind_after: null,
				last_seen_at: tutorialCompletedAt,
				completed_at: tutorialCompletedAt,
			},
			{ onConflict: "user_id" },
		),
		`Seed tutorial preference for ${account.email}`,
	);
	await userClient.auth.signOut();
};

const seedTestAccounts = async (environment) => {
	const admin = createClient(environment.apiUrl, environment.serviceRoleKey, {
		auth: {
			autoRefreshToken: false,
			detectSessionInUrl: false,
			persistSession: false,
		},
		realtime: { transport: WebSocket },
	});
	const listedUsers = await waitForLocalServices(admin);
	const usersByEmail = new Map(
		listedUsers.users.map((user) => [user.email?.toLowerCase(), user]),
	);

	for (const account of testAccounts) {
		let user = usersByEmail.get(account.email);
		if (user) {
			user = requireSuccessfulResult(
				await admin.auth.admin.updateUserById(user.id, {
					password: account.password,
					user_metadata: { display_name: account.displayName },
				}),
				`Update ${account.email}`,
			).user;
		} else {
			user = requireSuccessfulResult(
				await admin.auth.admin.createUser({
					email: account.email,
					password: account.password,
					email_confirm: true,
					user_metadata: { display_name: account.displayName },
				}),
				`Create ${account.email}`,
			).user;
		}

		requireSuccessfulResult(
			await admin.from("profiles").upsert(
				{
					user_id: user.id,
					display_name: account.displayName,
				},
				{ onConflict: "user_id" },
			),
			`Seed profile for ${account.email}`,
		);

		if (account.role) {
			requireSuccessfulResult(
				await admin.from("app_role_assignments").upsert(
					{
						user_id: user.id,
						role: account.role,
					},
					{ onConflict: "user_id" },
				),
				`Seed role for ${account.email}`,
			);
		} else {
			requireSuccessfulResult(
				await admin.from("app_role_assignments").delete().eq("user_id", user.id),
				`Clear role for ${account.email}`,
			);
		}

		await seedTestTutorialPreference(environment, account, user.id);
	}
};

const startLocalStack = async ({
	seedAccounts = true,
	applyMigrations = true,
	applyReferenceFixtures = true,
} = {}) => {
	ensureContainerRuntime();
	console.log("Starting isolated local Supabase test stack...");
	runCommand("supabase", [
		"start",
		"--exclude",
		"edge-runtime,logflare,vector",
	], { capture: true });
	if (applyMigrations) {
		console.log("Applying pending local database migrations...");
		runCommand("supabase", ["migration", "up", "--local"]);
	}
	if (applyReferenceFixtures) await applyLocalQaSeed();
	const environment = getLocalEnvironment();
	await writeTestEnvironment(environment);
	if (seedAccounts) await seedTestAccounts(environment);
	return environment;
};

const resetLocalStack = async () => {
	await startLocalStack({
		seedAccounts: false,
		applyMigrations: false,
		applyReferenceFixtures: false,
	});
	runCommand("supabase", ["db", "reset", "--local"]);
	await restartLocalGateway();
	await applyLocalQaSeed();
	const environment = getLocalEnvironment();
	await writeTestEnvironment(environment);
	await seedTestAccounts(environment);
};

const printAccounts = () => {
	console.log("Local QA accounts:");
	for (const account of testAccounts) {
		console.log(`- ${account.email} (${account.role ?? "user"})`);
	}
	console.log(`- Password: ${testAccounts[0].password}`);
};

const main = async () => {
	switch (action) {
		case "start":
			await startLocalStack();
			printAccounts();
			break;
		case "reset":
			await resetLocalStack();
			printAccounts();
			break;
		case "verify":
			await resetLocalStack();
			runCommand("supabase", ["test", "db", "--local"]);
			printAccounts();
			break;
		case "status":
			ensureContainerRuntime();
			{
				const values = parseStatusEnvironment(
					runCommand("supabase", ["status", "-o", "env"], { capture: true }),
				);
				console.log(`Local API: ${values.API_URL ?? "unavailable"}`);
				console.log(`Local Studio: ${values.STUDIO_URL ?? "unavailable"}`);
				console.log(`Test environment: ${testEnvironmentPath}`);
			}
			break;
		case "stop":
			ensureContainerRuntime();
			runCommand("supabase", ["stop"]);
			break;
		default:
			throw new Error(`Unknown test database action: ${action}`);
	}
};

main().catch((error) => {
	console.error(error instanceof Error ? error.message : error);
	process.exitCode = 1;
});
