import type { FdcFood } from "$lib/utils/food/types";
import type { IngredientProvenanceOption } from "$lib/utils/ingredients/ingredientProvenance";
import type { FoodPreferenceProfile } from "$lib/utils/profile/foodPreferenceProfile";
import type { SmoothieListKey } from "$lib/utils/storage/client/smoothieLists";

export type SavedIngredientListProps = {
	activeList: SmoothieListKey;
	foods: FdcFood[];
	provenanceOptions?: readonly IngredientProvenanceOption[];
	activeRawCount?: number;
	listLoading?: boolean;
	loadingMoreList?: SmoothieListKey | null;
	canRevealMore?: boolean;
	selectedFoodId?: number | null;
	selectedIds?: number[];
	selectionMode?: boolean;
	removingItem?: string | null;
	movingItem?: string | null;
	moving?: boolean;
	revealPaused?: boolean;
	preferenceProfile?: FoodPreferenceProfile | null;
	resetKey?: number;
	onSelectAll: () => void;
	onEnterSelection: (foodId?: number) => void;
	onCancelSelection: () => void;
	onMoveSelection: () => boolean | Promise<boolean>;
	onMoveItem: (food: FdcFood) => void | Promise<void>;
	onToggle: (foodId: number) => void;
	onPreview: (food: FdcFood) => void;
	onActions: (food: FdcFood) => void;
	onRemove: (foodId: number) => void;
	onRevealMore: () => void | Promise<void>;
};
