insert into public.nutrient_source_mappings (
	source_key,
	source_nutrient_key,
	source_unit_name,
	source_nutrient_name,
	nutrient_id,
	priority,
	mapping_method,
	confidence,
	enabled,
	observation_count,
	first_observed_at,
	last_observed_at,
	provenance
)
select
	'uk-cofid',
	mapping.source_nutrient_key,
	mapping.source_unit_name,
	mapping.source_nutrient_name,
	mapping.nutrient_id,
	10,
	'standards_dataset',
	1,
	true,
	0,
	now(),
	now(),
	jsonb_build_object(
		'datasetKey', 'cofid-2021',
		'mappingBasis', 'CoFID source tag and documented nutrient definition'
	)
from (values
	('WATER', 'G', 'Water', 1051::bigint),
	('TOTNIT', 'G', 'Total nitrogen', 1002::bigint),
	('PROT', 'G', 'Protein', 1003::bigint),
	('FAT', 'G', 'Fat', 1004::bigint),
	('CHO', 'G', 'Carbohydrate', 1005::bigint),
	('KCALS', 'KCAL', 'Energy', 1008::bigint),
	('KJ', 'KJ', 'Energy', 1062::bigint),
	('STAR', 'G', 'Starch', 1009::bigint),
	('TOTSUG', 'G', 'Total sugars', 2000::bigint),
	('GLUC', 'G', 'Glucose', 1011::bigint),
	('GALACT', 'G', 'Galactose', 1075::bigint),
	('FRUCT', 'G', 'Fructose', 1012::bigint),
	('SUCR', 'G', 'Sucrose', 1010::bigint),
	('MALT', 'G', 'Maltose', 1014::bigint),
	('LACT', 'G', 'Lactose', 1013::bigint),
	('ALCO', 'G', 'Alcohol', 1018::bigint),
	('AOACFIB', 'G', 'AOAC fibre', 1079::bigint),
	('SATFOD', 'G', 'Saturated fatty acids per 100g food', 1258::bigint),
	('MONOFOD', 'G', 'Monounsaturated fatty acids per 100g food', 1292::bigint),
	('POLYFOD', 'G', 'Polyunsaturated fatty acids per 100g food', 1293::bigint),
	('FODTRANS', 'G', 'Total trans fatty acids per 100g food', 1257::bigint),
	('CHOL', 'MG', 'Cholesterol', 1253::bigint),
	('NA', 'MG', 'Sodium', 1093::bigint),
	('K', 'MG', 'Potassium', 1092::bigint),
	('CA', 'MG', 'Calcium', 1087::bigint),
	('MG', 'MG', 'Magnesium', 1090::bigint),
	('P', 'MG', 'Phosphorus', 1091::bigint),
	('FE', 'MG', 'Iron', 1089::bigint),
	('CU', 'MG', 'Copper', 1098::bigint),
	('ZN', 'MG', 'Zinc', 1095::bigint),
	('MN', 'MG', 'Manganese', 1101::bigint),
	('SE', 'UG', 'Selenium', 1103::bigint),
	('I', 'UG', 'Iodine', 1100::bigint),
	('RET', 'UG', 'Retinol', 1105::bigint),
	('VITD', 'UG', 'Total Vitamin D', 1114::bigint),
	('VITE', 'MG', 'Total Vitamin E', 1158::bigint),
	('VITK1', 'UG', 'Phylloquinone', 1185::bigint),
	('THIA', 'MG', 'Thiamin', 1165::bigint),
	('RIBO', 'MG', 'Riboflavin', 1166::bigint),
	('NIAC', 'MG', 'Niacin', 1167::bigint),
	('NIACEQU', 'MG', 'Niacin equivalent', 700409::bigint),
	('VITB6', 'MG', 'Vitamin B6', 1175::bigint),
	('VITB12', 'UG', 'Vitamin B12', 1178::bigint),
	('FOLT', 'UG', 'Folate', 1177::bigint),
	('PANTO', 'MG', 'Pantothenate', 1170::bigint),
	('BIOT', 'UG', 'Biotin', 1176::bigint),
	('VITC', 'MG', 'Vitamin C', 1162::bigint),
	('ACAR', 'UG', 'Alpha-carotene', 1108::bigint),
	('BCAR', 'UG', 'Beta-carotene', 1107::bigint),
	('LUT', 'UG', 'Lutein', 1121::bigint),
	('LYCO', 'UG', 'Lycopene', 1122::bigint),
	('25OHD3', 'UG', '25-hydroxy vitamin D3', 700329::bigint),
	('VITD3', 'UG', 'Cholecalciferol', 1112::bigint),
	('ATOPH', 'MG', 'Alpha-tocopherol', 1109::bigint),
	('BTOPH', 'MG', 'Beta-tocopherol', 1125::bigint),
	('DTOPH', 'MG', 'Delta-tocopherol', 1127::bigint),
	('GTOPH', 'MG', 'Gamma-tocopherol', 1126::bigint),
	('ATOTR', 'MG', 'Alpha-tocotrienol', 1128::bigint),
	('GTOTR', 'MG', 'Gamma-tocotrienol', 1130::bigint),
	('PHYTO', 'MG', 'Phytosterol', 1283::bigint),
	('BSITPHYTO', 'MG', 'Beta-sitosterol', 700641::bigint),
	('CAMPHYTO', 'MG', 'Campesterol', 700639::bigint),
	('STIGPHYTO', 'MG', 'Stigmasterol', 700638::bigint)
) as mapping(
	source_nutrient_key,
	source_unit_name,
	source_nutrient_name,
	nutrient_id
)
on conflict (source_key, source_nutrient_key, source_unit_name) do update
set
	source_nutrient_name = excluded.source_nutrient_name,
	nutrient_id = excluded.nutrient_id,
	priority = excluded.priority,
	mapping_method = excluded.mapping_method,
	confidence = excluded.confidence,
	enabled = excluded.enabled,
	last_observed_at = excluded.last_observed_at,
	provenance = excluded.provenance;
